server:
  port: ${PORT:8078}
  servlet:
    context-path:

spring:
  application:
    name: ecommerce-shopping-cart-api
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: ${SHOW_SQL:true}
    database-platform: H2

logging.level.org.hibernate.type: TRACE

shopping-cart:
  costs:
    costPerDelivery: ${COST_PER_DELIVERY:1.2}
    costPerProduct: ${COST_PER_PRODUCT:0.5}
    fixedCost: ${FIXED_COST:2.99}

hikarids:
  connectionTimeout: 10000
  maxPoolSize: 10
  poolName: hikaridp
  username: ${DB_USERNAME:ecommerce_app_usr}
  password: ${DB_PASSWORD:ecommerce_app_usr}